### ISSUE TITLE
Parsing SAMI fails with unicode objects as input

### ISSUE THREAD

**Issue by shahriman** [pbs/pycaption#18]
This is how the traceback looks like:
```
>>> from pycaption import SAMIReader 
>>> s = open("example.sami").read()
>>> SAMIReader().read(s)
/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py:269: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (len(data) >= 4) and (data[:2] == b'\xfe\xff') \
/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py:273: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif (len(data) >= 4) and (data[:2] == b'\xff\xfe') \
/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py:277: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:3] == b'\xef\xbb\xbf':
/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py:280: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:4] == b'\x00\x00\xfe\xff':
/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py:283: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif data[:4] == b'\xff\xfe\x00\x00':
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shakkhar/subtitles/pycaption/pycaption/sami.py", line 36, in read
    sami_soup = BeautifulSoup(content)
  File "/usr/local/shakkhar/lib/python2.7/site-packages/bs4/__init__.py", line 193, in __init__
    self.builder.prepare_markup(markup, from_encoding)):
  File "/usr/local/shakkhar/lib/python2.7/site-packages/bs4/builder/_lxml.py", line 99, in prepare_markup
    for encoding in detector.encodings:
  File "/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py", line 256, in encodings
    self.chardet_encoding = chardet_dammit(self.markup)
  File "/usr/local/shakkhar/lib/python2.7/site-packages/bs4/dammit.py", line 31, in chardet_dammit
    return chardet.detect(s)['encoding']
  File "/usr/local/shakkhar/lib/python2.7/site-packages/chardet/__init__.py", line 25, in detect
    raise ValueError('Expected a bytes object, not a unicode object')
ValueError: Expected a bytes object, not a unicode object
```

BeautifulSoup uses chardet to detect encoding. chardet [requires](https://github.com/chardet/chardet/blob/master/chardet/__init__.py#L22) that the input data be a `bytes` object.

This issue is probably library verison / python version / platform specific. Here are the details of my setup:

CentOS release 6.4 (Final)
Python 2.7.5
beautifulsoup4==4.3.2
lxml==3.2.3
chardet==2.2.1

The test file can be obtained from [here](https://dl.dropboxusercontent.com/u/32117554/example.sami).

**Comment by vladiibine** [comment]
The example file is not available anymore. 
@shahriman can you please post it again, somewhere, so I can check if the issue is still occurring? A lot of stuff has happened in the mean time with pycaption, so this might be closable.

**Comment by shahriman** [comment]
Sorry I don't have that file anymore. You can close the issue.

**Comment by vladiibine** [comment]
cool, thanks for the heads up
